"""
VeriAssist v2.0 — Coverage Model Generator

Takes CoverageAnalysis results and generates:
  1. Complete SystemVerilog covergroup code
  2. Sequence recommendations to close gaps
  3. Coverage checklist for verification planning

Uses the opportunities identified by CoverageAnalyzer to produce
production-quality covergroups with protocol-aware bins, transition
coverage, cross coverage, and illegal bins.
"""

import logging
from typing import Optional
from dataclasses import dataclass, field

from app.services.coverage_analyzer import (
    CoverageAnalysis,
    CoverageOpportunity,
    FSMInfo,
    coverage_analyzer,
    format_analysis_summary,
)
from app.services.interface_parser import ParsedInterface, Signal

logger = logging.getLogger("veriassist.coverage_gen")


# ═══════════════════════════════════════════════════════════════
# DATA STRUCTURES
# ═══════════════════════════════════════════════════════════════

@dataclass
class SequenceRecommendation:
    """A recommended test sequence to close a coverage gap."""
    name: str
    description: str
    priority: str = "medium"
    target_coverage: list[str] = field(default_factory=list)
    sequence_code: str = ""


@dataclass
class CoverageModel:
    """Complete generated coverage model."""
    covergroup_code: str = ""
    subscriber_code: str = ""
    recommendations: list[SequenceRecommendation] = field(default_factory=list)
    checklist: list[dict] = field(default_factory=list)
    analysis_summary: str = ""
    total_coverpoints: int = 0
    total_crosses: int = 0
    generation_time: float = 0.0


# ═══════════════════════════════════════════════════════════════
# COVERAGE GENERATOR
# ═══════════════════════════════════════════════════════════════

class CoverageGenerator:
    """Generates SystemVerilog coverage models from analysis results."""

    def generate(
        self,
        dut_code: str,
        iface: Optional[ParsedInterface] = None,
        protocol: str = "",
        name: str = "",
    ) -> CoverageModel:
        """
        Full pipeline: analyze DUT → generate coverage model.

        Args:
            dut_code: DUT SystemVerilog source
            iface: Optional parsed interface
            protocol: Protocol hint
            name: Base name for coverage components

        Returns:
            CoverageModel with covergroup code, recommendations, checklist
        """
        import time
        t0 = time.time()

        # Step 1: Analyze
        analysis = coverage_analyzer.analyze(dut_code, iface, protocol)
        if not name:
            name = analysis.module_name or "dut"

        # Step 2: Generate covergroup
        cg_code, cp_count, cx_count = self._generate_covergroup(name, analysis, iface)

        # Step 3: Generate subscriber wrapper
        sub_code = self._generate_subscriber(name, analysis)

        # Step 4: Generate sequence recommendations
        recs = self._generate_recommendations(name, analysis, iface)

        # Step 5: Generate checklist
        checklist = self._generate_checklist(analysis)

        model = CoverageModel(
            covergroup_code=cg_code,
            subscriber_code=sub_code,
            recommendations=recs,
            checklist=checklist,
            analysis_summary=format_analysis_summary(analysis),
            total_coverpoints=cp_count,
            total_crosses=cx_count,
            generation_time=time.time() - t0,
        )

        logger.info(
            f"Generated coverage model: {name}, "
            f"{cp_count} coverpoints, {cx_count} crosses, "
            f"{len(recs)} recommendations"
        )

        return model

    # ═══════════════════════════════════════════════════════
    # COVERGROUP GENERATION
    # ═══════════════════════════════════════════════════════

    def _generate_covergroup(
        self,
        name: str,
        analysis: CoverageAnalysis,
        iface: Optional[ParsedInterface],
    ) -> tuple[str, int, int]:
        """Generate complete covergroup code. Returns (code, coverpoint_count, cross_count)."""

        lines = []
        cp_count = 0
        cx_count = 0

        lines.append(f"// ═══════════════════════════════════════════════════")
        lines.append(f"// Coverage Model for {name} ({analysis.protocol})")
        lines.append(f"// Auto-generated by VeriAssist v2.0")
        lines.append(f"// Opportunities: {analysis.total_opportunities}")
        lines.append(f"// ═══════════════════════════════════════════════════")
        lines.append("")

        # Main covergroup
        lines.append(f"covergroup {name}_cg with function sample(")
        lines.append(f"    // Transaction or signal inputs")

        # Build sample arguments from interface signals
        sample_args = []
        if iface:
            for sig in iface.signals:
                if sig.is_clock or sig.is_reset:
                    continue
                width = f"[{sig.msb}:{sig.lsb}]" if sig.width > 1 else ""
                sample_args.append(f"    bit {width} {sig.name}")
        else:
            # Fallback: use signals from opportunities
            seen = set()
            for opp in analysis.opportunities:
                for s in opp.signals:
                    if s not in seen:
                        sample_args.append(f"    bit {s}")
                        seen.add(s)

        lines.append(",\n".join(sample_args))
        lines.append(f");")
        lines.append("")

        # ── FSM coverpoints ──
        for fsm in analysis.fsms:
            lines.append(f"    // --- FSM: {fsm.state_reg} ---")

            # State coverage
            lines.append(f"    cp_{fsm.state_reg}: coverpoint {fsm.state_reg} {{")
            for s in fsm.states:
                lines.append(f"        bins {s['name']} = {{{s['value']}}};")

            # Illegal bins if no default
            if not fsm.has_default and fsm.width > 0:
                max_val = 2 ** fsm.width - 1
                defined = len(fsm.states)
                if defined < max_val + 1:
                    lines.append(f"        illegal_bins illegal = {{[{defined}:{max_val}]}};")

            lines.append(f"    }}")
            cp_count += 1
            lines.append("")

            # Transition coverage
            if fsm.transitions:
                lines.append(f"    cp_{fsm.state_reg}_trans: coverpoint {fsm.state_reg} {{")
                for t in fsm.transitions:
                    safe_name = f"{t['from_state']}_to_{t['to_state']}"
                    lines.append(f"        bins {safe_name} = ({t['from_state']} => {t['to_state']});")
                lines.append(f"    }}")
                cp_count += 1
                lines.append("")

        # ── Signal coverpoints ──
        if iface:
            # Control signals
            ctrl_names = []
            for sig in iface.control_signals:
                if sig.direction == "input":
                    lines.append(f"    cp_{sig.name}: coverpoint {sig.name};")
                    ctrl_names.append(sig.name)
                    cp_count += 1

            # Data signals with range bins
            data_names = []
            for sig in iface.data_signals:
                if sig.width <= 1:
                    lines.append(f"    cp_{sig.name}: coverpoint {sig.name};")
                elif sig.width <= 8:
                    lines.append(f"    cp_{sig.name}: coverpoint {sig.name} {{")
                    lines.append(f"        bins zero = {{0}};")
                    lines.append(f"        bins low  = {{[1:{2**(sig.width-1)-1}]}};")
                    lines.append(f"        bins high = {{[{2**(sig.width-1)}:{2**sig.width-2}]}};")
                    lines.append(f"        bins max  = {{{2**sig.width-1}}};")
                    lines.append(f"    }}")
                else:
                    quarter = 2**sig.width // 4
                    lines.append(f"    cp_{sig.name}: coverpoint {sig.name} {{")
                    lines.append(f"        bins zero    = {{0}};")
                    lines.append(f"        bins q1      = {{[1:{quarter-1}]}};")
                    lines.append(f"        bins q2      = {{[{quarter}:{2*quarter-1}]}};")
                    lines.append(f"        bins q3      = {{[{2*quarter}:{3*quarter-1}]}};")
                    lines.append(f"        bins q4      = {{[{3*quarter}:{2**sig.width-2}]}};")
                    lines.append(f"        bins max_val = {{{2**sig.width-1}}};")
                    lines.append(f"    }}")
                data_names.append(sig.name)
                cp_count += 1

            lines.append("")

            # Address signals
            for sig in iface.address_signals:
                if sig.width >= 4:
                    lines.append(f"    cp_{sig.name}_align: coverpoint {sig.name}[1:0] {{")
                    lines.append(f"        bins aligned   = {{0}};")
                    lines.append(f"        bins unaligned = {{[1:3]}};")
                    lines.append(f"    }}")
                    cp_count += 1

            # Status signals
            for sig in iface.output_signals:
                if sig.group == "status":
                    lines.append(f"    cp_{sig.name}: coverpoint {sig.name};")
                    cp_count += 1

            lines.append("")

            # ── Cross coverage ──
            lines.append(f"    // --- Cross Coverage ---")

            # Control × control
            if len(ctrl_names) >= 2:
                cross_names = ctrl_names[:3]
                lines.append(f"    cx_ctrl: cross " + ", ".join(f"cp_{n}" for n in cross_names) + ";")
                cx_count += 1

            # Control × data (first of each)
            if ctrl_names and data_names:
                lines.append(f"    cx_ctrl_data: cross cp_{ctrl_names[0]}, cp_{data_names[0]};")
                cx_count += 1

            # Protocol-specific crosses
            if analysis.protocol == "fifo":
                if "wr_en" in ctrl_names and "rd_en" in ctrl_names:
                    lines.append(f"    cx_wr_rd: cross cp_wr_en, cp_rd_en;")
                    cx_count += 1

        lines.append("")
        lines.append(f"endgroup")

        return "\n".join(lines), cp_count, cx_count

    # ═══════════════════════════════════════════════════════
    # SUBSCRIBER WRAPPER
    # ═══════════════════════════════════════════════════════

    def _generate_subscriber(self, name: str, analysis: CoverageAnalysis) -> str:
        """Generate a uvm_subscriber class that samples the covergroup."""

        lines = []
        lines.append(f"class {name}_coverage_model extends uvm_subscriber #({name}_transaction);")
        lines.append(f"    `uvm_component_utils({name}_coverage_model)")
        lines.append("")
        lines.append(f"    {name}_cg cg;")
        lines.append("")
        lines.append(f"    function new(string name, uvm_component parent);")
        lines.append(f"        super.new(name, parent);")
        lines.append(f"        cg = new();")
        lines.append(f"    endfunction")
        lines.append("")
        lines.append(f"    function void write({name}_transaction t);")
        lines.append(f"        cg.sample(")

        # Build sample call with transaction fields
        sample_fields = []
        for opp in analysis.opportunities:
            for s in opp.signals:
                if s not in [f.split(".")[-1] for f in sample_fields]:
                    sample_fields.append(f"            t.{s}")

        # Deduplicate
        seen = set()
        unique_fields = []
        for f in sample_fields:
            if f not in seen:
                unique_fields.append(f)
                seen.add(f)

        lines.append(",\n".join(unique_fields[:20]))  # limit to avoid huge arg lists
        lines.append(f"        );")
        lines.append(f"    endfunction")
        lines.append("")

        lines.append(f"    function void report_phase(uvm_phase phase);")
        lines.append(f"        super.report_phase(phase);")
        lines.append(f'        `uvm_info("COV", $sformatf("Coverage: %.1f%%", cg.get_coverage()), UVM_NONE)')
        lines.append(f"    endfunction")
        lines.append("")
        lines.append(f"endclass")

        return "\n".join(lines)

    # ═══════════════════════════════════════════════════════
    # SEQUENCE RECOMMENDATIONS
    # ═══════════════════════════════════════════════════════

    def _generate_recommendations(
        self,
        name: str,
        analysis: CoverageAnalysis,
        iface: Optional[ParsedInterface],
    ) -> list[SequenceRecommendation]:
        """Generate sequence recommendations to close coverage gaps."""
        recs = []

        # High-priority opportunities get sequence recommendations
        for opp in analysis.get_by_priority("high"):
            if opp.sequence_hint:
                rec = SequenceRecommendation(
                    name=f"seq_{opp.name.replace(' ', '_').replace('(', '').replace(')', '').lower()[:40]}",
                    description=opp.sequence_hint,
                    priority="high",
                    target_coverage=[opp.name],
                )

                # Generate sequence code for some categories
                if opp.category == "protocol_specific" and "back-to-back" in opp.name.lower():
                    rec.sequence_code = self._gen_back_to_back_seq(name)
                elif opp.category == "protocol_specific" and "fill level" in opp.name.lower():
                    rec.sequence_code = self._gen_fill_level_seq(name)
                elif opp.category == "protocol_specific" and "overflow" in opp.name.lower():
                    rec.sequence_code = self._gen_overflow_seq(name)

                recs.append(rec)

        # FSM-specific sequences
        for fsm in analysis.fsms:
            if fsm.transitions:
                rec = SequenceRecommendation(
                    name=f"seq_{fsm.state_reg}_all_transitions",
                    description=f"Exercise all {len(fsm.transitions)} transitions of FSM '{fsm.state_reg}'",
                    priority="high",
                    target_coverage=[f"FSM transition coverage ({fsm.state_reg})"],
                    sequence_code=self._gen_fsm_walk_seq(name, fsm),
                )
                recs.append(rec)

        # Boundary value sequence
        if iface and iface.data_signals:
            rec = SequenceRecommendation(
                name=f"seq_{name}_boundary_values",
                description="Test boundary values (0, max, mid) for all data signals",
                priority="medium",
                target_coverage=["Data boundary"],
                sequence_code=self._gen_boundary_seq(name, iface),
            )
            recs.append(rec)

        # Reset recovery sequence
        rec = SequenceRecommendation(
            name=f"seq_{name}_reset_recovery",
            description="Apply reset mid-transaction and verify clean recovery",
            priority="medium",
            target_coverage=["Reset during operation"],
            sequence_code=self._gen_reset_recovery_seq(name),
        )
        recs.append(rec)

        return recs

    # ═══════════════════════════════════════════════════════
    # SEQUENCE CODE GENERATORS
    # ═══════════════════════════════════════════════════════

    def _gen_back_to_back_seq(self, name: str) -> str:
        return f"""class {name}_back_to_back_seq extends uvm_sequence #({name}_transaction);
    `uvm_object_utils({name}_back_to_back_seq)
    function new(string name = "{name}_back_to_back_seq");
        super.new(name);
    endfunction
    task body();
        {name}_transaction txn;
        // Send 20 transactions with no idle cycles
        repeat(20) begin
            txn = {name}_transaction::type_id::create("txn");
            start_item(txn);
            assert(txn.randomize());
            finish_item(txn);
            // No delay between transactions
        end
    endtask
endclass"""

    def _gen_fill_level_seq(self, name: str) -> str:
        return f"""class {name}_fill_level_seq extends uvm_sequence #({name}_transaction);
    `uvm_object_utils({name}_fill_level_seq)
    function new(string name = "{name}_fill_level_seq");
        super.new(name);
    endfunction
    task body();
        {name}_transaction txn;
        // Fill to each level: 1, half, almost-full, full
        foreach (int level in '{{1, 4, 7, 8}}) begin
            // Write 'level' items
            repeat(level) begin
                txn = {name}_transaction::type_id::create("txn");
                start_item(txn);
                assert(txn.randomize() with {{ is_write == 1; }});
                finish_item(txn);
            end
            // Read all back
            repeat(level) begin
                txn = {name}_transaction::type_id::create("txn");
                start_item(txn);
                assert(txn.randomize() with {{ is_write == 0; }});
                finish_item(txn);
            end
        end
    endtask
endclass"""

    def _gen_overflow_seq(self, name: str) -> str:
        return f"""class {name}_overflow_seq extends uvm_sequence #({name}_transaction);
    `uvm_object_utils({name}_overflow_seq)
    function new(string name = "{name}_overflow_seq");
        super.new(name);
    endfunction
    task body();
        {name}_transaction txn;
        // Fill FIFO completely (8 writes for DEPTH=8)
        repeat(8) begin
            txn = {name}_transaction::type_id::create("txn");
            start_item(txn);
            assert(txn.randomize() with {{ is_write == 1; }});
            finish_item(txn);
        end
        // Attempt one more write (should be blocked by DUT)
        txn = {name}_transaction::type_id::create("txn");
        start_item(txn);
        assert(txn.randomize() with {{ is_write == 1; }});
        finish_item(txn);
        `uvm_info("OVF_SEQ", "Overflow attempt complete", UVM_MEDIUM)
    endtask
endclass"""

    def _gen_fsm_walk_seq(self, name: str, fsm: FSMInfo) -> str:
        lines = []
        lines.append(f"class {name}_fsm_walk_seq extends uvm_sequence #({name}_transaction);")
        lines.append(f"    `uvm_object_utils({name}_fsm_walk_seq)")
        lines.append(f'    function new(string name = "{name}_fsm_walk_seq");')
        lines.append(f"        super.new(name);")
        lines.append(f"    endfunction")
        lines.append(f"    task body();")
        lines.append(f"        {name}_transaction txn;")
        lines.append(f"        // Walk through all FSM states: {' -> '.join(s['name'] for s in fsm.states)}")
        lines.append(f"        repeat(3) begin // run full cycle 3 times")
        lines.append(f"            repeat({len(fsm.states) + 2}) begin")
        lines.append(f'                txn = {name}_transaction::type_id::create("txn");')
        lines.append(f"                start_item(txn);")
        lines.append(f"                assert(txn.randomize());")
        lines.append(f"                finish_item(txn);")
        lines.append(f"            end")
        lines.append(f"        end")
        lines.append(f"    endtask")
        lines.append(f"endclass")
        return "\n".join(lines)

    def _gen_boundary_seq(self, name: str, iface: ParsedInterface) -> str:
        lines = []
        lines.append(f"class {name}_boundary_seq extends uvm_sequence #({name}_transaction);")
        lines.append(f"    `uvm_object_utils({name}_boundary_seq)")
        lines.append(f'    function new(string name = "{name}_boundary_seq");')
        lines.append(f"        super.new(name);")
        lines.append(f"    endfunction")
        lines.append(f"    task body();")
        lines.append(f"        {name}_transaction txn;")

        for sig in iface.data_signals:
            if sig.direction == "input" and sig.width > 1:
                max_val = 2**sig.width - 1
                mid_val = 2**(sig.width - 1)
                lines.append(f"        // Boundary values for {sig.name}")
                for val, label in [(0, "min"), (max_val, "max"), (mid_val, "mid")]:
                    lines.append(f'        txn = {name}_transaction::type_id::create("txn");')
                    lines.append(f"        start_item(txn);")
                    lines.append(f"        assert(txn.randomize() with {{ {sig.name} == {val}; }}); // {label}")
                    lines.append(f"        finish_item(txn);")

        lines.append(f"    endtask")
        lines.append(f"endclass")
        return "\n".join(lines)

    def _gen_reset_recovery_seq(self, name: str) -> str:
        return f"""class {name}_reset_recovery_seq extends uvm_sequence #({name}_transaction);
    `uvm_object_utils({name}_reset_recovery_seq)
    function new(string name = "{name}_reset_recovery_seq");
        super.new(name);
    endfunction
    task body();
        {name}_transaction txn;
        // Send a few transactions
        repeat(3) begin
            txn = {name}_transaction::type_id::create("txn");
            start_item(txn);
            assert(txn.randomize());
            finish_item(txn);
        end
        // NOTE: Reset assertion must be done from the test level
        // by driving the reset signal through the virtual interface.
        // This sequence only generates the post-reset traffic.
        `uvm_info("RST_SEQ", "Pre-reset transactions sent. Apply reset from test.", UVM_MEDIUM)
        // Post-reset transactions
        repeat(5) begin
            txn = {name}_transaction::type_id::create("txn");
            start_item(txn);
            assert(txn.randomize());
            finish_item(txn);
        end
    endtask
endclass"""

    # ═══════════════════════════════════════════════════════
    # COVERAGE CHECKLIST
    # ═══════════════════════════════════════════════════════

    def _generate_checklist(self, analysis: CoverageAnalysis) -> list[dict]:
        """Generate a coverage verification checklist."""
        checklist = []

        for opp in analysis.opportunities:
            checklist.append({
                "item": opp.name,
                "category": opp.category,
                "priority": opp.priority,
                "description": opp.description,
                "status": "not_started",  # not_started | in_progress | covered
                "coverpoint": opp.coverpoint_hint,
                "sequence": opp.sequence_hint,
            })

        # Sort by priority
        priority_order = {"high": 0, "medium": 1, "low": 2}
        checklist.sort(key=lambda x: priority_order.get(x["priority"], 3))

        return checklist


# ═══════════════════════════════════════════════════════════════
# SINGLETON
# ═══════════════════════════════════════════════════════════════

coverage_generator = CoverageGenerator()